-- Travian Puro Database Seeds
-- Initial data for Travian Puro Installation

-- Insert initial server statistics
INSERT INTO `server_stats` (`date`, `total_users`, `active_users`, `total_villages`, `total_population`) VALUES
(CURDATE(), 0, 0, 0, 0);

-- Insert default game settings (additional ones)
INSERT IGNORE INTO `game_settings` (`key`, `value`, `description`) VALUES
('server_name', 'Travian Puro Server', 'Server display name'),
('server_description', 'A Travian Puro server', 'Server description'),
('server_rules', 'No cheating, no multi-accounting, respect other players', 'Server rules'),
('admin_email', 'admin@travianpuro.com', 'Administrator email'),
('maintenance_mode', '0', 'Maintenance mode on/off'),
('maintenance_message', 'Server under maintenance. Please try again later.', 'Maintenance message'),
('registration_message', 'Welcome to Travian Puro!', 'Registration welcome message'),
('start_protection', '72', 'New player protection in hours'),
('natars_active', '0', 'Natars tribe active'),
('end_game_active', '0', 'End game active'),
('wonder_winner', '0', 'Wonder of the World winner alliance'),
('server_start_date', CURDATE(), 'Server start date'),
('server_end_date', DATE_ADD(CURDATE(), INTERVAL 1 YEAR), 'Server end date'),
('max_alliance_size', '50', 'Maximum alliance members'),
('alliance_creation_cost', '10000', 'Cost to create alliance'),
('village_rename_cost', '100', 'Cost to rename village'),
('resource_trade_ratio', '1.5', 'Resource trade ratio'),
('merchant_capacity', '500', 'Merchant carrying capacity'),
('merchants_per_market', '5', 'Number of merchants per market level'),
('troop_healing_rate', '0.1', 'Troop healing rate per hour'),
('building_destruction_rate', '0.5', 'Building destruction rate'),
('crop_consumption_rate', '1', 'Crop consumption rate'),
('celebration_cost', '10000', 'Celebration cost'),
('celebration_duration', '24', 'Celebration duration in hours'),
('research_cost_multiplier', '1', 'Research cost multiplier'),
('construction_cost_multiplier', '1', 'Construction cost multiplier'),
('troop_cost_multiplier', '1', 'Troop cost multiplier'),
('experience_rate', '1', 'Experience gain rate'),
('hero_revival_time', '24', 'Hero revival time in hours'),
('hero_attributes_max', '100', 'Maximum hero attributes'),
('artifact_spawn_rate', '0.01', 'Artifact spawn rate'),
('tournament_square_speed', '2', 'Tournament square speed bonus'),
('map_fog_of_war', '0', 'Fog of war enabled'),
('spy_reports', '1', 'Spy reports enabled'),
('battle_reports', '1', 'Battle reports enabled'),
('trade_reports', '1', 'Trade reports enabled'),
('construction_reports', '1', 'Construction reports enabled'),
('research_reports', '1', 'Research reports enabled'),
('alliance_reports', '1', 'Alliance reports enabled'),
('message_limit_per_hour', '10', 'Message limit per hour'),
('report_retention_days', '30', 'Report retention in days'),
('message_retention_days', '30', 'Message retention in days'),
('log_retention_days', '7', 'Log retention in days'),
('cache_cleanup_interval', '3600', 'Cache cleanup interval in seconds'),
('session_timeout', '7200', 'Session timeout in seconds'),
('login_attempts_limit', '5', 'Failed login attempts limit'),
('login_lockout_time', '900', 'Login lockout time in seconds'),
('password_min_length', '8', 'Minimum password length'),
('username_min_length', '3', 'Minimum username length'),
('username_max_length', '20', 'Maximum username length'),
('village_name_min_length', '3', 'Minimum village name length'),
('village_name_max_length', '30', 'Maximum village name length'),
('alliance_name_min_length', '3', 'Minimum alliance name length'),
('alliance_name_max_length', '20', 'Maximum alliance name length'),
('alliance_tag_min_length', '2', 'Minimum alliance tag length'),
('alliance_tag_max_length', '5', 'Maximum alliance tag length'),
('message_subject_max_length', '100', 'Maximum message subject length'),
('message_content_max_length', '1000', 'Maximum message content length'),
('report_title_max_length', '200', 'Maximum report title length'),
('report_content_max_length', '5000', 'Maximum report content length'),
('market_offer_max_amount', '100000', 'Maximum market offer amount'),
('market_min_trade_ratio', '0.5', 'Minimum market trade ratio'),
('market_max_trade_ratio', '3', 'Maximum market trade ratio'),
('troop_movement_speed_base', '1', 'Base troop movement speed'),
('troop_movement_speed_cavalry', '2', 'Cavalry movement speed multiplier'),
('troop_movement_speed_siege', '0.5', 'Siege weapon movement speed multiplier'),
('building_construction_time_base', '1', 'Base building construction time'),
('building_construction_time_main', '0.5', 'Main building construction time multiplier'),
('building_construction_time_palace', '2', 'Palace construction time multiplier'),
('resource_production_base', '1', 'Base resource production'),
('resource_production_bonus', '0.25', 'Resource production bonus per level'),
('storage_capacity_base', '80000', 'Base storage capacity'),
('storage_capacity_bonus', '1000', 'Storage capacity bonus per level'),
('crop_consumption_base', '1', 'Base crop consumption per troop'),
('crop_consumption_cavalry', '2', 'Cavalry crop consumption multiplier'),
('crop_consumption_siege', '3', 'Siege weapon crop consumption multiplier'),
('troop_training_time_base', '1', 'Base troop training time'),
('troop_training_time_barracks', '1', 'Barracks training time multiplier'),
('troop_training_time_stable', '1.5', 'Stable training time multiplier'),
('troop_training_time_workshop', '2', 'Workshop training time multiplier'),
('research_time_base', '1', 'Base research time'),
('research_time_academy', '1', 'Academy research time multiplier'),
('celebration_type_small', 'small', 'Small celebration type'),
('celebration_type_large', 'large', 'Large celebration type'),
('celebration_bonus_small', '200', 'Small celebration culture points bonus'),
('celebration_bonus_large', '1000', 'Large celebration culture points bonus'),
('culture_points_per_village', '1', 'Culture points per village'),
('culture_points_per_population', '0.01', 'Culture points per population'),
('alliance_creation_culture_points', '10000', 'Culture points required for alliance creation'),
('village_expansion_culture_points', '1000', 'Culture points required for village expansion'),
('max_villages_per_player', '10', 'Maximum villages per player'),
('village_expansion_distance', '30', 'Maximum distance for village expansion'),
('village_expansion_cost_base', '750', 'Base cost for village expansion'),
('village_expansion_cost_multiplier', '1.5', 'Cost multiplier for each additional village'),
('wonder_construction_time', '100', 'Wonder construction time in hours'),
('wonder_levels', '50', 'Number of wonder levels'),
('wonder_villages_count', '13', 'Number of wonder villages'),
('wonder_activation_level', '50', 'Wonder activation level'),
('end_game_duration', '168', 'End game duration in hours'),
('natars_attack_interval', '24', 'Natars attack interval in hours'),
('natars_troop_strength', '2', 'Natars troop strength multiplier'),
('artifact_spawn_interval', '168', 'Artifact spawn interval in hours'),
('artifact_duration', '168', 'Artifact duration in hours'),
('artifact_types', 'attack,defense,building,speed,resource', 'Available artifact types'),
('artifact_strength', '1.5', 'Artifact strength multiplier'),
('hero_experience_rate', '1', 'Hero experience gain rate'),
('hero_level_max', '100', 'Maximum hero level'),
('hero_attributes_points_per_level', '5', 'Hero attribute points per level'),
('hero_revival_cost_base', '100', 'Base hero revival cost'),
('hero_revival_cost_multiplier', '1.5', 'Hero revival cost multiplier'),
('spy_success_rate_base', '0.5', 'Base spy success rate'),
('spy_detection_rate_base', '0.3', 'Base spy detection rate'),
('spy_cost_base', '100', 'Base spy cost'),
('spy_cost_multiplier', '1.5', 'Spy cost multiplier'),
('battle_calculation_version', '1', 'Battle calculation version'),
('battle_rounds_max', '100', 'Maximum battle rounds'),
('battle_flee_rate', '0.1', 'Battle flee rate'),
('battle_morale_effect', '0.2', 'Battle morale effect'),
('battle_terrain_effect', '0.1', 'Battle terrain effect'),
('battle_weather_effect', '0.05', 'Battle weather effect'),
('battle_luck_factor', '0.05', 'Battle luck factor'),
('battle_experience_rate', '1', 'Battle experience gain rate'),
('battle_report_detail_level', 'full', 'Battle report detail level'),
('troop_upkeep_rate', '1', 'Troop upkeep rate'),
('troop_upkeep_cavalry', '2', 'Cavalry upkeep multiplier'),
('troop_upkeep_siege', '3', 'Siege weapon upkeep multiplier'),
('troop_upkeep_hero', '5', 'Hero upkeep multiplier'),
('market_merchant_speed', '1', 'Market merchant speed'),
('market_trade_duration_base', '1', 'Base market trade duration'),
('market_trade_duration_distance', '1', 'Market trade duration per distance'),
('market_fee_rate', '0.1', 'Market fee rate'),
('market_fee_min', '1', 'Minimum market fee'),
('market_fee_max', '10000', 'Maximum market fee'),
('alliance_diplomacy_types', 'peace,war,confederation', 'Available alliance diplomacy types'),
('alliance_diplomacy_change_cooldown', '24', 'Alliance diplomacy change cooldown in hours'),
('alliance_invite_timeout', '168', 'Alliance invite timeout in hours'),
('alliance_kick_cooldown', '24', 'Alliance kick cooldown in hours'),
('alliance_leader_transfer_cooldown', '168', 'Alliance leader transfer cooldown in hours'),
('player_ranking_update_interval', '3600', 'Player ranking update interval in seconds'),
('alliance_ranking_update_interval', '3600', 'Alliance ranking update interval in seconds'),
('village_ranking_update_interval', '3600', 'Village ranking update interval in seconds'),
('resource_update_interval', '60', 'Resource update interval in seconds'),
('population_update_interval', '300', 'Population update interval in seconds'),
('construction_update_interval', '60', 'Construction update interval in seconds'),
'troop_training_update_interval', '60', 'Troop training update interval in seconds'),
('battle_update_interval', '60', 'Battle update interval in seconds'),
('market_update_interval', '60', 'Market update interval in seconds'),
('message_cleanup_interval', '3600', 'Message cleanup interval in seconds'),
('report_cleanup_interval', '3600', 'Report cleanup interval in seconds'),
('session_cleanup_interval', '300', 'Session cleanup interval in seconds'),
('cache_cleanup_interval', '3600', 'Cache cleanup interval in seconds'),
('statistics_update_interval', '3600', 'Statistics update interval in seconds'),
('ranking_update_interval', '3600', 'Ranking update interval in seconds'),
('backup_interval', '86400', 'Backup interval in seconds'),
('backup_retention_days', '7', 'Backup retention in days'),
('log_level', 'info', 'Log level'),
('debug_mode', '0', 'Debug mode on/off'),
('performance_monitoring', '0', 'Performance monitoring on/off'),
('error_reporting', '1', 'Error reporting on/off'),
('email_notifications', '1', 'Email notifications on/off'),
('sms_notifications', '0', 'SMS notifications on/off'),
('push_notifications', '0', 'Push notifications on/off'),
('api_enabled', '1', 'API enabled on/off'),
('api_rate_limit', '100', 'API rate limit per hour'),
('api_key_required', '1', 'API key required on/off'),
('mobile_version', '1', 'Mobile version enabled on/off'),
('responsive_design', '1', 'Responsive design enabled on/off'),
('dark_mode', '0', 'Dark mode enabled on/off'),
('language_selection', '1', 'Language selection enabled on/off'),
('timezone_selection', '1', 'Timezone selection enabled on/off'),
('currency_selection', '0', 'Currency selection enabled on/off'),
('theme_selection', '1', 'Theme selection enabled on/off'),
('sound_effects', '1', 'Sound effects enabled on/off'),
('music_enabled', '0', 'Music enabled on/off'),
('animations_enabled', '1', 'Animations enabled on/off'),
('tooltips_enabled', '1', 'Tooltips enabled on/off'),
('tutorials_enabled', '1', 'Tutorials enabled on/off'),
('help_system', '1', 'Help system enabled on/off'),
('faq_enabled', '1', 'FAQ enabled on/off'),
('wiki_enabled', '1', 'Wiki enabled on/off'),
('forum_enabled', '1', 'Forum enabled on/off'),
('chat_enabled', '1', 'Chat enabled on/off'),
('private_messaging', '1', 'Private messaging enabled on/off'),
('public_messaging', '1', 'Public messaging enabled on/off'),
('alliance_messaging', '1', 'Alliance messaging enabled on/off'),
('system_messaging', '1', 'System messaging enabled on/off'),
('notification_system', '1', 'Notification system enabled on/off'),
('alert_system', '1', 'Alert system enabled on/off'),
('warning_system', '1', 'Warning system enabled on/off'),
('error_system', '1', 'Error system enabled on/off'),
('logging_system', '1', 'Logging system enabled on/off'),
('audit_system', '1', 'Audit system enabled on/off'),
('monitoring_system', '1', 'Monitoring system enabled on/off'),
('analytics_system', '1', 'Analytics system enabled on/off'),
('reporting_system', '1', 'Reporting system enabled on/off'),
('dashboard_system', '1', 'Dashboard system enabled on/off'),
('admin_panel', '1', 'Admin panel enabled on/off'),
('moderator_panel', '1', 'Moderator panel enabled on/off'),
('player_panel', '1', 'Player panel enabled on/off'),
('guest_panel', '1', 'Guest panel enabled on/off'),
('registration_system', '1', 'Registration system enabled on/off'),
('login_system', '1', 'Login system enabled on/off'),
('logout_system', '1', 'Logout system enabled on/off'),
('password_reset_system', '1', 'Password reset system enabled on/off'),
('email_verification_system', '0', 'Email verification system enabled on/off'),
('account_activation_system', '0', 'Account activation system enabled on/off'),
('account_deletion_system', '1', 'Account deletion system enabled on/off'),
('account_suspension_system', '1', 'Account suspension system enabled on/off'),
('account_banning_system', '1', 'Account banning system enabled on/off'),
('account_merging_system', '0', 'Account merging system enabled on/off'),
('account_transfer_system', '0', 'Account transfer system enabled on/off'),
('character_creation_system', '1', 'Character creation system enabled on/off'),
('character_deletion_system', '1', 'Character deletion system enabled on/off'),
('character_transfer_system', '0', 'Character transfer system enabled on/off'),
('village_creation_system', '1', 'Village creation system enabled on/off'),
('village_deletion_system', '1', 'Village deletion system enabled on/off'),
('village_transfer_system', '0', 'Village transfer system enabled on/off'),
('building_construction_system', '1', 'Building construction system enabled on/off'),
('building_destruction_system', '1', 'Building destruction system enabled on/off'),
('building_upgrade_system', '1', 'Building upgrade system enabled on/off'),
('building_downgrade_system', '1', 'Building downgrade system enabled on/off'),
('troop_training_system', '1', 'Troop training system enabled on/off'),
('troop_disband_system', '1', 'Troop disband system enabled on/off'),
('troop_transfer_system', '1', 'Troop transfer system enabled on/off'),
('battle_system', '1', 'Battle system enabled on/off'),
('raid_system', '1', 'Raid system enabled on/off'),
'siege_system', '1', 'Siege system enabled on/off'),
('reinforcement_system', '1', 'Reinforcement system enabled on/off'),
('retreat_system', '1', 'Retreat system enabled on/off'),
('surrender_system', '1', 'Surrender system enabled on/off'),
('trading_system', '1', 'Trading system enabled on/off'),
('market_system', '1', 'Market system enabled on/off'),
('auction_system', '0', 'Auction system enabled on/off'),
('exchange_system', '0', 'Exchange system enabled on/off'),
('banking_system', '0', 'Banking system enabled on/off'),
('taxation_system', '0', 'Taxation system enabled on/off'),
('alliance_system', '1', 'Alliance system enabled on/off'),
('diplomacy_system', '1', 'Diplomacy system enabled on/off'),
('war_system', '1', 'War system enabled on/off'),
('peace_system', '1', 'Peace system enabled on/off'),
('confederation_system', '1', 'Confederation system enabled on/off'),
('non_aggression_pact_system', '1', 'Non-aggression pact system enabled on/off'),
('messaging_system', '1', 'Messaging system enabled on/off'),
('notification_system', '1', 'Notification system enabled on/off'),
('alert_system', '1', 'Alert system enabled on/off'),
('warning_system', '1', 'Warning system enabled on/off'),
('error_system', '1', 'Error system enabled on/off'),
('logging_system', '1', 'Logging system enabled on/off'),
('audit_system', '1', 'Audit system enabled on/off'),
('monitoring_system', '1', 'Monitoring system enabled on/off'),
('analytics_system', '1', 'Analytics system enabled on/off'),
('reporting_system', '1', 'Reporting system enabled on/off'),
('dashboard_system', '1', 'Dashboard system enabled on/off'),
('admin_panel', '1', 'Admin panel enabled on/off'),
('moderator_panel', '1', 'Moderator panel enabled on/off'),
('player_panel', '1', 'Player panel enabled on/off'),
('guest_panel', '1', 'Guest panel enabled on/off'),
('registration_system', '1', 'Registration system enabled on/off'),
('login_system', '1', 'Login system enabled on/off'),
('logout_system', '1', 'Logout system enabled on/off'),
('password_reset_system', '1', 'Password reset system enabled on/off'),
('email_verification_system', '0', 'Email verification system enabled on/off'),
('account_activation_system', '0', 'Account activation system enabled on/off'),
('account_deletion_system', '1', 'Account deletion system enabled on/off'),
('account_suspension_system', '1', 'Account suspension system enabled on/off'),
('account_banning_system', '1', 'Account banning system enabled on/off'),
('account_merging_system', '0', 'Account merging system enabled on/off'),
('account_transfer_system', '0', 'Account transfer system enabled on/off'),
('character_creation_system', '1', 'Character creation system enabled on/off'),
('character_deletion_system', '1', 'Character deletion system enabled on/off'),
('character_transfer_system', '0', 'Character transfer system enabled on/off'),
('village_creation_system', '1', 'Village creation system enabled on/off'),
('village_deletion_system', '1', 'Village deletion system enabled on/off'),
('village_transfer_system', '0', 'Village transfer system enabled on/off'),
('building_construction_system', '1', 'Building construction system enabled on/off'),
('building_destruction_system', '1', 'Building destruction system enabled on/off'),
('building_upgrade_system', '1', 'Building upgrade system enabled on/off'),
('building_downgrade_system', '1', 'Building downgrade system enabled on/off'),
('troop_training_system', '1', 'Troop training system enabled on/off'),
('troop_disband_system', '1', 'Troop disband system enabled on/off'),
('troop_transfer_system', '1', 'Troop transfer system enabled on/off'),
('battle_system', '1', 'Battle system enabled on/off'),
('raid_system', '1', 'Raid system enabled on/off'),
('siege_system', '1', 'Siege system enabled on/off'),
('reinforcement_system', '1', 'Reinforcement system enabled on/off'),
('retreat_system', '1', 'Retreat system enabled on/off'),
('surrender_system', '1', 'Surrender system enabled on/off'),
('trading_system', '1', 'Trading system enabled on/off'),
('market_system', '1', 'Market system enabled on/off'),
('auction_system', '0', 'Auction system enabled on/off'),
('exchange_system', '0', 'Exchange system enabled on/off'),
('banking_system', '0', 'Banking system enabled on/off'),
('taxation_system', '0', 'Taxation system enabled on/off'),
('alliance_system', '1', 'Alliance system enabled on/off'),
('diplomacy_system', '1', 'Diplomacy system enabled on/off'),
('war_system', '1', 'War system enabled on/off'),
('peace_system', '1', 'Peace system enabled on/off'),
('confederation_system', '1', 'Confederation system enabled on/off'),
('non_aggression_pact_system', '1', 'Non-aggression pact system enabled on/off'),
('messaging_system', '1', 'Messaging system enabled on/off'),
('notification_system', '1', 'Notification system enabled on/off'),
('alert_system', '1', 'Alert system enabled on/off'),
('warning_system', '1', 'Warning system enabled on/off'),
('error_system', '1', 'Error system enabled on/off'),
('logging_system', '1', 'Logging system enabled on/off'),
('audit_system', '1', 'Audit system enabled on/off'),
('monitoring_system', '1', 'Monitoring system enabled on/off'),
('analytics_system', '1', 'Analytics system enabled on/off'),
('reporting_system', '1', 'Reporting system enabled on/off'),
('dashboard_system', '1', 'Dashboard system enabled on/off'),
('admin_panel', '1', 'Admin panel enabled on/off'),
('moderator_panel', '1', 'Moderator panel enabled on/off'),
('player_panel', '1', 'Player panel enabled on/off'),
('guest_panel', '1', 'Guest panel enabled on/off'),
('registration_system', '1', 'Registration system enabled on/off'),
('login_system', '1', 'Login system enabled on/off'),
('logout_system', '1', 'Logout system enabled on/off'),
('password_reset_system', '1', 'Password reset system enabled on/off'),
('email_verification_system', '0', 'Email verification system enabled on/off'),
('account_activation_system', '0', 'Account activation system enabled on/off'),
('account_deletion_system', '1', 'Account deletion system enabled on/off'),
('account_suspension_system', '1', 'Account suspension system enabled on/off'),
('account_banning_system', '1', 'Account banning system enabled on/off'),
('account_merging_system', '0', 'Account merging system enabled on/off'),
('account_transfer_system', '0', 'Account transfer system enabled on/off'),
('character_creation_system', '1', 'Character creation system enabled on/off'),
('character_deletion_system', '1', 'Character deletion system enabled on/off'),
('character_transfer_system', '0', 'Character transfer system enabled on/off'),
('village_creation_system', '1', 'Village creation system enabled on/off'),
('village_deletion_system', '1', 'Village deletion system enabled on/off'),
('village_transfer_system', '0', 'Village transfer system enabled on/off'),
('building_construction_system', '1', 'Building construction system enabled on/off'),
('building_destruction_system', '1', 'Building destruction system enabled on/off'),
('building_upgrade_system', '1', 'Building upgrade system enabled on/off'),
('building_downgrade_system', '1', 'Building downgrade system enabled on/off'),
('troop_training_system', '1', 'Troop training system enabled on/off'),
('troop_disband_system', '1', 'Troop disband system enabled on/off'),
('troop_transfer_system', '1', 'Troop transfer system enabled on/off'),
('battle_system', '1', 'Battle system enabled on/off'),
('raid_system', '1', 'Raid system enabled on/off'),
('siege_system', '1', 'Siege system enabled on/off'),
('reinforcement_system', '1', 'Reinforcement system enabled on/off'),
('retreat_system', '1', 'Retreat system enabled on/off'),
('surrender_system', '1', 'Surrender system enabled on/off'),
('trading_system', '1', 'Trading system enabled on/off'),
('market_system', '1', 'Market system enabled on/off'),
('auction_system', '0', 'Auction system enabled on/off'),
('exchange_system', '0', 'Exchange system enabled on/off'),
('banking_system', '0', 'Banking system enabled on/off'),
('taxation_system', '0', 'Taxation system enabled on/off'),
('alliance_system', '1', 'Alliance system enabled on/off'),
('diplomacy_system', '1', 'Diplomacy system enabled on/off'),
('war_system', '1', 'War system enabled on/off'),
('peace_system', '1', 'Peace system enabled on/off'),
('confederation_system', '1', 'Confederation system enabled on/off'),
('non_aggression_pact_system', '1', 'Non-aggression pact system enabled on/off');
