<?php

/**
 *  Puro Installer - Step 2: Database Configuration
 */

// Check if already installed
if (file_exists(config_path('database.php'))) {
    header('Location: ../');
    exit;
}

// Process form submission
$errors = [];
$success = false;

if ($_POST) {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_port = $_POST['db_port'] ?? '3306';
    $db_database = $_POST['db_database'] ?? '';
    $db_username = $_POST['db_username'] ?? '';
    $db_password = $_POST['db_password'] ?? '';

    // Validation
    if (empty($db_host)) $errors[] = 'Host do banco de dados é obrigatório';
    if (empty($db_database)) $errors[] = 'Nome do banco de dados é obrigatório';
    if (empty($db_username)) $errors[] = 'Usuário do banco de dados é obrigatório';

    if (empty($errors)) {
        try {
            // Test database connection
            $dsn = "mysql:host={$db_host};port={$db_port};charset=utf8mb4";
            $pdo = new PDO($dsn, $db_username, $db_password);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // Check if database exists
            $stmt = $pdo->query("SHOW DATABASES LIKE '{$db_database}'");
            if ($stmt->rowCount() == 0) {
                // Create database
                $pdo->exec("CREATE DATABASE `{$db_database}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            }

            // Test connection to database
            $dsn = "mysql:host={$db_host};port={$db_port};dbname={$db_database};charset=utf8mb4";
            $pdo = new PDO($dsn, $db_username, $db_password);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // Import database schema
            $schema_file = storage_path('database/schema.sql');
            if (file_exists($schema_file)) {
                $schema = file_get_contents($schema_file);
                $statements = array_filter(array_map('trim', explode(';', $schema)));

                foreach ($statements as $statement) {
                    if (!empty($statement)) {
                        $pdo->exec($statement);
                    }
                }
            }

            // Create database configuration file
            $db_config = "<?php\n\n";
            $db_config .= "/**\n";
            $db_config .= " * Database Configuration\n";
            $db_config .= " * Generated by installer on: " . date('Y-m-d H:i:s') . "\n";
            $db_config .= " */\n\n";
            $db_config .= "return [\n";
            $db_config .= "    'host' => '{$db_host}',\n";
            $db_config .= "    'port' => '{$db_port}',\n";
            $db_config .= "    'database' => '{$db_database}',\n";
            $db_config .= "    'username' => '{$db_username}',\n";
            $db_config .= "    'password' => '{$db_password}',\n";
            $db_config .= "    'charset' => 'utf8mb4',\n";
            $db_config .= "    'collation' => 'utf8mb4_unicode_ci',\n";
            $db_config .= "    'prefix' => '',\n";
            $db_config .= "    'strict' => true,\n";
            $db_config .= "    'engine' => 'InnoDB',\n";
            $db_config .= "    'options' => [\n";
            $db_config .= "        PDO::ATTR_CASE => PDO::CASE_NATURAL,\n";
            $db_config .= "        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n";
            $db_config .= "        PDO::ATTR_ORACLE_NULLS => PDO::NULL_NATURAL,\n";
            $db_config .= "        PDO::ATTR_STRINGIFY_FETCHES => false,\n";
            $db_config .= "        PDO::ATTR_EMULATE_PREPARES => false,\n";
            $db_config .= "        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n";
            $db_config .= "    ]\n";
            $db_config .= "];\n";

            file_put_contents(config_path('database.php'), $db_config);

            $success = true;
        } catch (PDOException $e) {
            $errors[] = 'Erro na conexão com o banco de dados: ' . $e->getMessage();
        }
    }
}

?>
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Puro - Configuração do Banco de Dados</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background: #1a1a1a;
            color: #fff;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .header h1 {
            font-size: 2.5em;
            color: #4CAF50;
            margin-bottom: 10px;
        }

        .header p {
            color: #ccc;
            font-size: 1.1em;
        }

        .card {
            background: #2a2a2a;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
            border: 1px solid #444;
        }

        .card h2 {
            color: #4CAF50;
            margin-bottom: 15px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            color: #ccc;
        }

        .form-group input {
            width: 100%;
            padding: 12px;
            background: #444;
            border: 1px solid #666;
            border-radius: 5px;
            color: #fff;
            font-size: 1em;
        }

        .form-group input:focus {
            outline: none;
            border-color: #4CAF50;
        }

        .btn {
            display: inline-block;
            padding: 12px 30px;
            background: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-size: 1.1em;
            border: none;
            cursor: pointer;
        }

        .btn:hover {
            background: #45a049;
        }

        .btn-secondary {
            background: #666;
        }

        .btn-secondary:hover {
            background: #555;
        }

        .error {
            color: #f44336;
            margin: 10px 0;
            padding: 10px;
            background: rgba(244, 67, 54, 0.1);
            border: 1px solid #f44336;
            border-radius: 5px;
        }

        .success {
            color: #4CAF50;
            margin: 10px 0;
            padding: 10px;
            background: rgba(76, 175, 80, 0.1);
            border: 1px solid #4CAF50;
            border-radius: 5px;
        }

        .progress {
            background: #444;
            height: 5px;
            border-radius: 3px;
            margin: 20px 0;
        }

        .progress-bar {
            background: #4CAF50;
            height: 100%;
            width: 50%;
            border-radius: 3px;
        }

        .step-indicator {
            text-align: center;
            margin-bottom: 30px;
        }

        .step {
            display: inline-block;
            width: 30px;
            height: 30px;
            background: #444;
            border-radius: 50%;
            line-height: 30px;
            margin: 0 5px;
        }

        .step.active {
            background: #4CAF50;
        }

        .step.completed {
            background: #666;
        }

        .form-row {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

        .help-text {
            font-size: 0.9em;
            color: #999;
            margin-top: 5px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>🏰 Puro</h1>
            <p>Configuração do Banco de Dados</p>
        </div>

        <div class="step-indicator">
            <span class="step completed">1</span>
            <span class="step active">2</span>
            <span class="step">3</span>
            <span class="step">4</span>
        </div>

        <div class="progress">
            <div class="progress-bar"></div>
        </div>

        <?php if ($success): ?>
            <div class="card" style="border-color: #4CAF50;">
                <h2 style="color: #4CAF50;">✅ Configuração Concluída!</h2>
                <p>O banco de dados foi configurado com sucesso!</p>
                <ul style="margin: 20px 0; padding-left: 20px;">
                    <li>Conexão testada e aprovada</li>
                    <li>Banco de dados criado/importado</li>
                    <li>Arquivo de configuração salvo</li>
                </ul>
                <div style="text-align: center; margin-top: 20px;">
                    <a href="settings.php" class="btn">Próximo Passo →</a>
                </div>
            </div>
        <?php else: ?>

            <div class="card">
                <h2>🗄️ Configuração do Banco de Dados</h2>
                <p>Preencha as informações do seu banco de dados MySQL.</p>

                <?php if (!empty($errors)): ?>
                    <div class="error">
                        <?php foreach ($errors as $error): ?>
                            <p>• <?= $error ?></p>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <form method="POST">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="db_host">Host do Banco de Dados</label>
                            <input type="text" id="db_host" name="db_host" value="<?= $_POST['db_host'] ?? 'localhost' ?>" required>
                            <div class="help-text">Ex: localhost ou 127.0.0.1</div>
                        </div>

                        <div class="form-group">
                            <label for="db_port">Porta</label>
                            <input type="number" id="db_port" name="db_port" value="<?= $_POST['db_port'] ?? '3306' ?>" required>
                            <div class="help-text">Porta padrão MySQL: 3306</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="db_database">Nome do Banco de Dados</label>
                        <input type="text" id="db_database" name="db_database" value="<?= $_POST['db_database'] ?? '_puro' ?>" required>
                        <div class="help-text">O banco será criado automaticamente se não existir</div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="db_username">Usuário</label>
                            <input type="text" id="db_username" name="db_username" value="<?= $_POST['db_username'] ?? 'root' ?>" required>
                            <div class="help-text">Usuário com permissão para criar banco de dados</div>
                        </div>

                        <div class="form-group">
                            <label for="db_password">Senha</label>
                            <input type="password" id="db_password" name="db_password" value="<?= $_POST['db_password'] ?? '' ?>">
                            <div class="help-text">Deixe em branco se não tiver senha</div>
                        </div>
                    </div>

                    <div style="text-align: center; margin-top: 30px;">
                        <a href="index.php" class="btn btn-secondary">← Voltar</a>
                        <button type="submit" class="btn">Testar e Salvar Configuração</button>
                    </div>
                </form>
            </div>

            <div class="card">
                <h2>💡 Dicas Importantes</h2>
                <ul style="list-style: none; margin: 20px 0;">
                    <li>✅ O usuário precisa ter permissão para criar bancos de dados</li>
                    <li>✅ O banco de dados será criado automaticamente</li>
                    <li>✅ As tabelas serão importadas automaticamente</li>
                    <li>✅ O arquivo de configuração será salvo em /config/database.php</li>
                </ul>
            </div>

        <?php endif; ?>
    </div>
</body>

</html>
