<?php

/**
 *  Puro Installer - Step 3: Advanced Settings
 */

// Check if database is configured
if (!file_exists(config_path('database.php'))) {
    header('Location: database.php');
    exit;
}

// Load database config
$db_config = config('database');

// Process form submission
$errors = [];
$success = false;

if ($_POST) {
    // App settings
    $app_name = $_POST['app_name'] ?? ' Puro';
    $app_url = $_POST['app_url'] ?? 'http://localhost/puro';
    $app_timezone = $_POST['app_timezone'] ?? 'America/Sao_Paulo';
    $app_locale = $_POST['app_locale'] ?? 'pt-br';
    $app_debug = isset($_POST['app_debug']) ? 'true' : 'false';
    $app_env = $_POST['app_env'] ?? 'local';

    // Cache settings
    $cache_enabled = isset($_POST['cache_enabled']) ? 'true' : 'false';
    $cache_driver = $_POST['cache_driver'] ?? 'file';

    // Security settings
    $force_https = isset($_POST['force_https']) ? 'true' : 'false';
    $csrf_enabled = isset($_POST['csrf_enabled']) ? 'true' : 'false';
    $rate_limiting = isset($_POST['rate_limiting']) ? 'true' : 'false';

    // Game settings
    $game_speed = $_POST['game_speed'] ?? '1';
    $max_players = $_POST['max_players'] ?? '1000';
    $map_size = $_POST['map_size'] ?? '400';
    $registration_enabled = isset($_POST['registration_enabled']) ? 'true' : 'false';

    // Generate app key
    $app_key = 'base64:' . base64_encode(random_bytes(32));

    try {
        // Create app configuration file
        $app_config = "<?php\n\n";
        $app_config .= "/**\n";
        $app_config .= " * Application Configuration\n";
        $app_config .= " * Generated by installer on: " . date('Y-m-d H:i:s') . "\n";
        $app_config .= " */\n\n";
        $app_config .= "return [\n";
        $app_config .= "    // Basic Settings\n";
        $app_config .= "    'name' => '{$app_name}',\n";
        $app_config .= "    'version' => '1.0.0',\n";
        $app_config .= "    'url' => '{$app_url}',\n";
        $app_config .= "    'timezone' => '{$app_timezone}',\n";
        $app_config .= "    'locale' => '{$app_locale}',\n";
        $app_config .= "    \n";
        $app_config .= "    // Environment\n";
        $app_config .= "    'env' => '{$app_env}',\n";
        $app_config .= "    'debug' => {$app_debug},\n";
        $app_config .= "    \n";
        $app_config .= "    // Security\n";
        $app_config .= "    'key' => '{$app_key}',\n";
        $app_config .= "    'cipher' => 'AES-256-CBC',\n";
        $app_config .= "    \n";
        $app_config .= "    // Session\n";
        $app_config .= "    'lifetime' => 120,\n";
        $app_config .= "    'expire_on_close' => false,\n";
        $app_config .= "    'secure' => {$force_https},\n";
        $app_config .= "    'httponly' => true,\n";
        $app_config .= "    'same_site' => 'lax',\n";
        $app_config .= "    \n";
        $app_config .= "    // Game Settings\n";
        $app_config .= "    'game' => [\n";
        $app_config .= "        'speed' => {$game_speed},\n";
        $app_config .= "        'start_date' => '" . date('Y-m-d') . "',\n";
        $app_config .= "        'end_date' => '" . date('Y-m-d', strtotime('+1 year')) . "',\n";
        $app_config .= "        'max_players' => {$max_players},\n";
        $app_config .= "        'map_size' => {$map_size},\n";
        $app_config .= "        'village_start_resources' => [\n";
        $app_config .= "            'wood' => 500,\n";
        $app_config .= "            'clay' => 500,\n";
        $app_config .= "            'iron' => 500,\n";
        $app_config .= "            'crop' => 500\n";
        $app_config .= "        ],\n";
        $app_config .= "        'max_storage' => 80000,\n";
        $app_config .= "        'max_crops' => 80000,\n";
        $app_config .= "    ],\n";
        $app_config .= "    \n";
        $app_config .= "    // Registration\n";
        $app_config .= "    'registration' => [\n";
        $app_config .= "        'enabled' => {$registration_enabled},\n";
        $app_config .= "        'require_email' => false,\n";
        $app_config .= "        'admin_approval' => false,\n";
        $app_config .= "        'max_accounts_per_ip' => 3,\n";
        $app_config .= "    ],\n";
        $app_config .= "];\n";

        file_put_contents(config_path('app.php'), $app_config);

        // Create cache configuration file
        $cache_config = "<?php\n\n";
        $cache_config .= "/**\n";
        $cache_config .= " * Cache Configuration\n";
        $cache_config .= " * Generated by installer on: " . date('Y-m-d H:i:s') . "\n";
        $cache_config .= " */\n\n";
        $cache_config .= "return [\n";
        $cache_config .= "    // Cache Settings\n";
        $cache_config .= "    'enabled' => {$cache_enabled},\n";
        $cache_config .= "    'default' => '{$cache_driver}',\n";
        $cache_config .= "    'prefix' => '_puro_',\n";
        $cache_config .= "    \n";
        $cache_config .= "    // File Cache\n";
        $cache_config .= "    'stores' => [\n";
        $cache_config .= "        'file' => [\n";
        $cache_config .= "            'driver' => 'file',\n";
        $cache_config .= "            'path' => __DIR__ . '/../storage/cache',\n";
        $cache_config .= "            'extension' => '.cache',\n";
        $cache_config .= "        ],\n";
        $cache_config .= "    ],\n";
        $cache_config .= "    \n";
        $cache_config .= "    // Cache TTL (seconds)\n";
        $cache_config .= "    'ttl' => [\n";
        $cache_config .= "        'default' => 3600,\n";
        $cache_config .= "        'short' => 300,\n";
        $cache_config .= "        'long' => 86400,\n";
        $cache_config .= "        'users' => 1800,\n";
        $cache_config .= "        'villages' => 3600,\n";
        $cache_config .= "        'statistics' => 300,\n";
        $cache_config .= "        'game_data' => 60,\n";
        $cache_config .= "    ],\n";
        $cache_config .= "];\n";

        file_put_contents(config_path('cache.php'), $cache_config);

        // Create security configuration file
        $security_config = "<?php\n\n";
        $security_config .= "/**\n";
        $security_config .= " * Security Configuration\n";
        $security_config .= " * Generated by installer on: " . date('Y-m-d H:i:s') . "\n";
        $security_config .= " */\n\n";
        $security_config .= "return [\n";
        $security_config .= "    // HTTPS Settings\n";
        $security_config .= "    'force_https' => {$force_https},\n";
        $security_config .= "    'secure_cookies' => {$force_https},\n";
        $security_config .= "    \n";
        $security_config .= "    // CSRF Protection\n";
        $security_config .= "    'csrf' => [\n";
        $security_config .= "        'enabled' => {$csrf_enabled},\n";
        $security_config .= "        'token_name' => '_token',\n";
        $security_config .= "        'header_name' => 'X-CSRF-TOKEN',\n";
        $security_config .= "        'expire' => 7200,\n";
        $security_config .= "    ],\n";
        $security_config .= "    \n";
        $security_config .= "    // Rate Limiting\n";
        $security_config .= "    'rate_limiting' => [\n";
        $security_config .= "        'enabled' => {$rate_limiting},\n";
        $security_config .= "        'requests_per_minute' => 60,\n";
        $security_config .= "        'requests_per_hour' => 1000,\n";
        $security_config .= "        'login_attempts' => 5,\n";
        $security_config .= "        'login_lockout' => 900,\n";
        $security_config .= "    ],\n";
        $security_config .= "];\n";

        file_put_contents(config_path('security.php'), $security_config);

        $success = true;
    } catch (Exception $e) {
        $errors[] = 'Erro ao salvar configurações: ' . $e->getMessage();
    }
}

// Timezones list
$timezones = [
    'America/Sao_Paulo' => 'São Paulo',
    'America/New_York' => 'New York',
    'Europe/London' => 'Londres',
    'Europe/Paris' => 'Paris',
    'Asia/Tokyo' => 'Tóquio',
    'Australia/Sydney' => 'Sydney'
];

// Locales list
$locales = [
    'pt-br' => 'Português (Brasil)',
    'en' => 'English',
    'es' => 'Español',
    'fr' => 'Français'
];

?>
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Puro - Configurações Avançadas</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background: #1a1a1a;
            color: #fff;
        }

        .container {
            max-width: 1000px;
            margin: 50px auto;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .header h1 {
            font-size: 2.5em;
            color: #4CAF50;
            margin-bottom: 10px;
        }

        .header p {
            color: #ccc;
            font-size: 1.1em;
        }

        .card {
            background: #2a2a2a;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
            border: 1px solid #444;
        }

        .card h2 {
            color: #4CAF50;
            margin-bottom: 15px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            color: #ccc;
        }

        .form-group input,
        .form-group select {
            width: 100%;
            padding: 12px;
            background: #444;
            border: 1px solid #666;
            border-radius: 5px;
            color: #fff;
            font-size: 1em;
        }

        .form-group input:focus,
        .form-group select:focus {
            outline: none;
            border-color: #4CAF50;
        }

        .checkbox-group {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }

        .checkbox-group input {
            width: auto;
            margin-right: 10px;
        }

        .btn {
            display: inline-block;
            padding: 12px 30px;
            background: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-size: 1.1em;
            border: none;
            cursor: pointer;
        }

        .btn:hover {
            background: #45a049;
        }

        .btn-secondary {
            background: #666;
        }

        .btn-secondary:hover {
            background: #555;
        }

        .error {
            color: #f44336;
            margin: 10px 0;
            padding: 10px;
            background: rgba(244, 67, 54, 0.1);
            border: 1px solid #f44336;
            border-radius: 5px;
        }

        .success {
            color: #4CAF50;
            margin: 10px 0;
            padding: 10px;
            background: rgba(76, 175, 80, 0.1);
            border: 1px solid #4CAF50;
            border-radius: 5px;
        }

        .progress {
            background: #444;
            height: 5px;
            border-radius: 3px;
            margin: 20px 0;
        }

        .progress-bar {
            background: #4CAF50;
            height: 100%;
            width: 75%;
            border-radius: 3px;
        }

        .step-indicator {
            text-align: center;
            margin-bottom: 30px;
        }

        .step {
            display: inline-block;
            width: 30px;
            height: 30px;
            background: #444;
            border-radius: 50%;
            line-height: 30px;
            margin: 0 5px;
        }

        .step.active {
            background: #4CAF50;
        }

        .step.completed {
            background: #666;
        }

        .form-row {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

        .help-text {
            font-size: 0.9em;
            color: #999;
            margin-top: 5px;
        }

        .tabs {
            display: flex;
            margin-bottom: 20px;
        }

        .tab {
            padding: 10px 20px;
            background: #444;
            border: 1px solid #666;
            border-bottom: none;
            cursor: pointer;
        }

        .tab.active {
            background: #4CAF50;
        }

        .tab-content {
            display: none;
        }

        .tab-content.active {
            display: block;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>🏰 Puro</h1>
            <p>Configurações Avançadas do Sistema</p>
        </div>

        <div class="step-indicator">
            <span class="step completed">1</span>
            <span class="step completed">2</span>
            <span class="step active">3</span>
            <span class="step">4</span>
        </div>

        <div class="progress">
            <div class="progress-bar"></div>
        </div>

        <?php if ($success): ?>
            <div class="card" style="border-color: #4CAF50;">
                <h2 style="color: #4CAF50;">✅ Configurações Salvas!</h2>
                <p>Todas as configurações foram salvas com sucesso!</p>
                <ul style="margin: 20px 0; padding-left: 20px;">
                    <li>Configurações da aplicação salvas</li>
                    <li>Configurações de cache salvas</li>
                    <li>Configurações de segurança salvas</li>
                    <li>Chave de aplicação gerada</li>
                </ul>
                <div style="text-align: center; margin-top: 20px;">
                    <a href="finish.php" class="btn">Próximo Passo →</a>
                </div>
            </div>
        <?php else: ?>

            <div class="card">
                <h2>⚙️ Configurações Avançadas</h2>
                <p>Configure as opções avançadas do sistema.</p>

                <?php if (!empty($errors)): ?>
                    <div class="error">
                        <?php foreach ($errors as $error): ?>
                            <p>• <?= $error ?></p>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <div class="tabs">
                    <div class="tab active" onclick="showTab('app')">📱 Aplicação</div>
                    <div class="tab" onclick="showTab('cache')">💾 Cache</div>
                    <div class="tab" onclick="showTab('security')">🔒 Segurança</div>
                    <div class="tab" onclick="showTab('game')">🎮 Jogo</div>
                </div>

                <form method="POST">
                    <!-- App Settings Tab -->
                    <div id="app-tab" class="tab-content active">
                        <div class="form-row">
                            <div class="form-group">
                                <label for="app_name">Nome do Servidor</label>
                                <input type="text" id="app_name" name="app_name" value="<?= $_POST['app_name'] ?? ' Puro' ?>" required>
                            </div>

                            <div class="form-group">
                                <label for="app_url">URL do Servidor</label>
                                <input type="url" id="app_url" name="app_url" value="<?= $_POST['app_url'] ?? 'http://localhost/puro' ?>" required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="app_timezone">Fuso Horário</label>
                                <select id="app_timezone" name="app_timezone">
                                    <?php foreach ($timezones as $value => $label): ?>
                                        <option value="<?= $value ?>" <?= (($_POST['app_timezone'] ?? 'America/Sao_Paulo') == $value) ? 'selected' : '' ?>>
                                            <?= $label ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="app_locale">Idioma Padrão</label>
                                <select id="app_locale" name="app_locale">
                                    <?php foreach ($locales as $value => $label): ?>
                                        <option value="<?= $value ?>" <?= (($_POST['app_locale'] ?? 'pt-br') == $value) ? 'selected' : '' ?>>
                                            <?= $label ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="app_env">Ambiente</label>
                                <select id="app_env" name="app_env">
                                    <option value="local" <?= (($_POST['app_env'] ?? 'local') == 'local') ? 'selected' : '' ?>>Local (Desenvolvimento)</option>
                                    <option value="production" <?= (($_POST['app_env'] ?? 'local') == 'production') ? 'selected' : '' ?>>Produção</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label>&nbsp;</label>
                                <div class="checkbox-group">
                                    <input type="checkbox" id="app_debug" name="app_debug" <?= isset($_POST['app_debug']) ? 'checked' : '' ?>>
                                    <label for="app_debug">Modo Debug</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Cache Settings Tab -->
                    <div id="cache-tab" class="tab-content">
                        <div class="checkbox-group">
                            <input type="checkbox" id="cache_enabled" name="cache_enabled" <?= !isset($_POST['cache_enabled']) || $_POST['cache_enabled'] ? 'checked' : '' ?>>
                            <label for="cache_enabled">Habilitar Cache</label>
                        </div>

                        <div class="form-group">
                            <label for="cache_driver">Driver de Cache</label>
                            <select id="cache_driver" name="cache_driver">
                                <option value="file" <?= (($_POST['cache_driver'] ?? 'file') == 'file') ? 'selected' : '' ?>>Arquivo (Recomendado)</option>
                                <option value="redis" <?= (($_POST['cache_driver'] ?? 'file') == 'redis') ? 'selected' : '' ?>>Redis</option>
                                <option value="memcached" <?= (($_POST['cache_driver'] ?? 'file') == 'memcached') ? 'selected' : '' ?>>Memcached</option>
                            </select>
                        </div>
                    </div>

                    <!-- Security Settings Tab -->
                    <div id="security-tab" class="tab-content">
                        <div class="checkbox-group">
                            <input type="checkbox" id="force_https" name="force_https" <?= isset($_POST['force_https']) ? 'checked' : '' ?>>
                            <label for="force_https">Forçar HTTPS</label>
                        </div>

                        <div class="checkbox-group">
                            <input type="checkbox" id="csrf_enabled" name="csrf_enabled" <?= !isset($_POST['csrf_enabled']) || $_POST['csrf_enabled'] ? 'checked' : '' ?>>
                            <label for="csrf_enabled">Proteção CSRF</label>
                        </div>

                        <div class="checkbox-group">
                            <input type="checkbox" id="rate_limiting" name="rate_limiting" <?= !isset($_POST['rate_limiting']) || $_POST['rate_limiting'] ? 'checked' : '' ?>>
                            <label for="rate_limiting">Limitação de Requisições</label>
                        </div>
                    </div>

                    <!-- Game Settings Tab -->
                    <div id="game-tab" class="tab-content">
                        <div class="form-row">
                            <div class="form-group">
                                <label for="game_speed">Velocidade do Jogo</label>
                                <select id="game_speed" name="game_speed">
                                    <option value="1" <?= (($_POST['game_speed'] ?? '1') == '1') ? 'selected' : '' ?>>Normal (1x)</option>
                                    <option value="2" <?= (($_POST['game_speed'] ?? '1') == '2') ? 'selected' : '' ?>>Rápido (2x)</option>
                                    <option value="3" <?= (($_POST['game_speed'] ?? '1') == '3') ? 'selected' : '' ?>>Super Rápido (3x)</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="max_players">Máximo de Jogadores</label>
                                <input type="number" id="max_players" name="max_players" value="<?= $_POST['max_players'] ?? '1000' ?>" min="10" max="10000">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="map_size">Tamanho do Mapa</label>
                                <select id="map_size" name="map_size">
                                    <option value="200" <?= (($_POST['map_size'] ?? '400') == '200') ? 'selected' : '' ?>>Pequeno (200x200)</option>
                                    <option value="400" <?= (($_POST['map_size'] ?? '400') == '400') ? 'selected' : '' ?>>Médio (400x400)</option>
                                    <option value="600" <?= (($_POST['map_size'] ?? '400') == '600') ? 'selected' : '' ?>>Grande (600x600)</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label>&nbsp;</label>
                                <div class="checkbox-group">
                                    <input type="checkbox" id="registration_enabled" name="registration_enabled" <?= !isset($_POST['registration_enabled']) || $_POST['registration_enabled'] ? 'checked' : '' ?>>
                                    <label for="registration_enabled">Permitir Novos Registros</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div style="text-align: center; margin-top: 30px;">
                        <a href="database.php" class="btn btn-secondary">← Voltar</a>
                        <button type="submit" class="btn">Salvar Configurações</button>
                    </div>
                </form>
            </div>

        <?php endif; ?>
    </div>

    <script>
        function showTab(tabName) {
            // Hide all tabs
            document.querySelectorAll('.tab-content').forEach(tab => {
                tab.classList.remove('active');
            });

            // Remove active class from all tab buttons
            document.querySelectorAll('.tab').forEach(tab => {
                tab.classList.remove('active');
            });

            // Show selected tab
            document.getElementById(tabName + '-tab').classList.add('active');

            // Add active class to clicked tab button
            event.target.classList.add('active');
        }
    </script>
</body>

</html>
